leicarentals/app/models/customer.py
import sys
from app.extensions import db
from datetime import datetime


class Customer(db.Model):
    __tablename__ = 'customers'

    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(140))
    last_name = db.Column(db.String(140))
    email = db.Column(db.String(140))
    is_signed_up = db.Column(db.Boolean, nullable=True)
    date_of_birth = db.Column(db.DateTime)
    membership_type_id = db.Column(
        db.Integer, db.ForeignKey('membership_types.id'))

    membership_type = db.relationship(
        'MembershipType'
    )

    @property
    def full_name(self):
        return '{0}, {1}'.format(self.last_name.title(),
                                 self.first_name.title())

    def from_dict(self, data):
        for field in ['first_name', 'last_name', 'email', 'date_of_birth',
                      'membership_type_id']:
            if field in data:
                setattr(self, field, data[field])

    def to_dict(self):
        data = {
            'id': self.id,
            'first_name': self.first_name,
            'last_name': self.last_name,
            'full_name': self.full_name,
            'email': self.email,
            'date_of_birth': self.date_of_birth,
            'membership_type_id': self.membership_type_id,
            'membership_type_name': self.membership_type.name
        }
        return data

leicarentals/app/customers/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Email
from wtforms.fields.html5 import DateField, EmailField


class CustomerForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email = EmailField('Email Address', validators=[DataRequired(),
                                                    Email()])
    newsletter = BooleanField('Newsletter')
    date_of_birth = DateField(
        'Birthdate', format='%Y-%m-%d', validators=[DataRequired()])
    membership_type_id = SelectField(
        'Membership Plan', coerce=int, validators=[DataRequired()])
    submit = SubmitField('Submit')

leicarentals/app/customers/__init__.py
from flask import Blueprint

customers = Blueprint('customers', __name__)

from app.customers import views

leicarentals/app/customers/views.py
import sys
from flask import (
    render_template,
    flash, redirect,
    url_for,
)
from flask_login import login_required
from app.customers.forms import CustomerForm
from app.extensions import db
from app.customers import customers
from app.models import (
    Customer,
    MembershipType,
)
from app.tasks import send_newsletter


@customers.before_request
@login_required
def require_login():
    pass


@customers.route('/')
@customers.route('/index')
@login_required
def index():
    customers = Customer.query.all()
    return render_template('customers/index.html',
                           customers=customers,
                           title='Customers')


@customers.route('/new', methods=['GET', 'POST'])
def new():
    membership_types = MembershipType.query \
        .all()
    form = CustomerForm()
    form.membership_type_id.choices = [
        (m.id, m.name) for m in membership_types]
    if form.validate_on_submit():
        customer = Customer()
        form.populate_obj(customer)
        db.session.add(customer)
        db.session.commit()
        flash('Customer added!', 'success')
        return redirect(url_for('customers.index'))

    return render_template('customers/new.html',
                           form=form,
                           title='Customers')


@customers.route('/edit/<id>', methods=['GET', 'POST'])
def edit(id):
    customer = Customer.query \
        .filter_by(id=id) \
        .first_or_404()
    membership_types = MembershipType.query \
        .all()
    form = CustomerForm(obj=customer)
    form.membership_type_id.choices = [
        (m.id, m.name) for m in membership_types]
    if form.validate_on_submit():
        form.populate_obj(customer)
        db.session.add(customer)
        db.session.commit()
        flash('Customer is updated!', 'success')
        return redirect(url_for('customers.index'))

    membership_types = MembershipType.query.all()
    return render_template('customers/edit.html',
                           membership_types=membership_types,
                           form=form,
                           title='Customers')


@customers.route('/details/<id>')
def details(id):
    customer = Customer.query \
        .filter_by(id=id) \
        .first_or_404()

    return render_template('customers/details.html',
                           customer=customer,
                           title='Customers')


@customers.route('/delete/<id>', methods=['POST'])
def delete(id):
    customer = Customer.query \
        .filter_by(id=id).first_or_404()
    db.session.delete(customer)
    db.session.commit()
    flash('Delete successfully.', 'success')

    return redirect(url_for('customers.index'))


@customers.route('/newsletter')
def newsletter():
    customers = \
        Customer.query.filter_by(is_signed_up=True).all()
    emails = [c.email for c in customers]
    names = [c.first_name for c in customers]
    for i in range(0, len(emails)):
        body = render_template(
            'email/newsletter.html', name=names[i])
        send_newsletter('LeicaRentals NewsLetter',
                        [emails[i]],
                        body)

    flash('Sending newsletters')

    return redirect(url_for('customers.index'))

leicarentals/app/templates/customers/details.html
{% extends "base.html" %}

{% block app_content %}
  <main class="container mt-4">
    <div class="col-lg-6 col-sm-12">
      <h2>{{ customer.full_name }}</h2>
      <ul class="list-group">
        <li class="list-group-item">Email: {{ customer.email }}</li>
        <li class="list-group-item">Membership Type: {{ customer.membership_type.name }}</li>
        <li class="list-group-item">Date of Birth: {{ customer.date_of_birth.strftime('%Y-%m-%d') }}</li>
        <li class="list-group-item">Newsletter: {{ customer.is_signed_up }}</li>
      </ul>
    </div>
  </main>
{% endblock %}

leicarentals/app/templates/customers/edit.html
{% extends "base.html" %}

{% block app_content %}
  <main class="container mt-4">
    <div class="col-lg-6 col-sm-12">
      <div class="mb-4">
        <h2 class="mb-3">Lens Form</h2>
      </div>
      <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.first_name.label }}
          {{ form.first_name(class_="form-control") }}
          {% for error in form.first_name.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.last_name.label }}
          {{ form.last_name(class_="form-control") }}
          {% for error in form.last_name.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.email.label }}
          {{ form.email(class_="form-control") }}
          {% for error in form.email.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.date_of_birth.label }}
          {{ form.date_of_birth(class_="form-control") }}
          {% for error in form.date_of_birth.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.membership_type_id.label }}
          {{ form.membership_type_id(class_="form-control") }}
          {% for error in form.membership_type_id.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
          <div class="checkbox mb-3">
            <label>
              <div type="checkbox" value="Newsletter">
                {{ form.newsletter() }} {{ form.newsletter.label }}
              </div>
            </label>
          </div>
        {{ form.submit(class="btn btn-primary") }}
      </div>
    </form>
  </main>
{% endblock %}

leicarentals/app/templates/customers/index.html
{% extends "base.html" %}

{% block app_content %}
  <main class="container mt-4">
    <h2>Customers</h2>
    <a href="{{ url_for('customers.new') }}" class="btn btn-link">Add New Customer</a>
    {% if customers %}
      <table id="customers" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
          <tr>
            <th>Customer</th>
            <th>Membership Type</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
      <tbody></tbody>
    </table>
  {% else %}
    <p>We don't have any customer yet.</p>
  {% endif %}
  </main>
{% endblock %}

{% block js %}
<script type="text/javascript">
  var csrf_token = "{{ csrf_token() }}";
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
    if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
      xhr.setRequestHeader("X-CSRFToken", csrf_token);
    }
  }
});
</script>

<script>
  $(document).ready(function () {
    var table = $("#customers").DataTable({
      ajax: {
        url: "/api/customers",
        dataSrc: ""
      },
      columns: [
        {
          data: "full_name",
          render: function(data, type, customer) {
            return "<a href='/customers/details/" + customer.id +
              "'>" + customer.full_name + "</a>";
          }
        },
        {
          data: "membership_type_name"
        },
        {
          render: function(data, type, customer) {
            return "<a href='/customers/edit/" + customer.id + "'class='btn btn-secondary btn-sm'>Edit</a>";
          }
        },
        {
          data: "id",
          render: function(data) {
            return "<button class='btn btn-secondary btn-sm js-delete' data-customer-id=" + data + ">Delete</button>";
          }
        }
      ]
    });
  });
</script>

<script>
  $("#customers").on("click", ".js-delete", function () {
    var button = $(this);
    bootbox.confirm("Are you sure you want to delete this customer?", function (result) {
      if (result) {
        $.ajax({
          url: "/api/customers/" + button.attr("data-customer-id"),
          method: "DELETE",
          success: function () {
            table.row(button.parents("tr")).remove().draw();
          }
        });
      }
    });
  });
</script>
{% endblock %}

leicarentals/app/templates/customers/new.html
{% extends "base.html" %}

{% block app_content %}
  <main class="container mt-4">
    <div class="col-lg-6 col-sm-12">
      <div class="mb-4">
        <h2 class="mb-3">Customer Form</h2>
      </div>
      <form id="newCustomerForm" action="" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.first_name.label }}
          {{ form.first_name(class_="form-control") }}
          {% for error in form.first_name.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.last_name.label }}
          {{ form.last_name(class_="form-control") }}
          {% for error in form.last_name.errors %}
            <span class="text-primary">{{ error }}</span>
         {% endfor %}
        </div>
        <div class="form-group">
          {{ form.email.label }}
          {{ form.email(class_="form-control") }}
          {% for error in form.email.errors %}
            <span class="text-primary">{{ error }}</span>
         {% endfor %}
        </div>
        <div class="form-group">
          {{ form.date_of_birth.label }}
          {{ form.date_of_birth(class_="form-control") }}
          {% for error in form.date_of_birth.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.membership_type_id.label }}
          {{ form.membership_type_id(class_="form-control") }}
          {% for error in form.membership_type_id.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
          <div class="checkbox mb-3">
            <label>
              <div type="checkbox" value="Newsletter">
                {{ form.newsletter() }} {{ form.newsletter.label }}
              </div>
            </label>
          </div>
        {{ form.submit(class="btn btn-primary") }}
      </form>
    </div>
  </main>
{% endblock %}