leicarentals/app/models/rental.py
from app.extensions import db
from datetime import datetime, date


class Rental(db.Model):
    __tablename__ = 'rentals'

    id = db.Column(db.Integer, primary_key=True)
    date_rented = db.Column(db.DateTime, default=datetime.utcnow)
    date_returned = db.Column(db.DateTime)
    customer_id = db.Column(db.Integer, db.ForeignKey('customers.id'))
    lens_id = db.Column(db.Integer, db.ForeignKey('lenses.id'))

    customer = db.relationship('Customer')
    lens = db.relationship('Lens')

    def from_dict(self, data):
        for field in ['date_rented', 'date_returned', 'customer_id',
                      'lens_id']:
            if field in data:
                setattr(self, field, data[field])

    def to_dict(self):
        data = {
            'id': self.id,
            'date_rented': self.date_rented.strftime('%Y-%m-%d'),
            'customer_name': self.customer.full_name,
            'lens_name': self.lens.lens_name
        }
        return data

leicarentals/app/rentals/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired


class RentalForm(FlaskForm):
    customer = StringField('Enter customer name', validators=[DataRequired()])
    lens = StringField('Enter lens', validators=[DataRequired()])

leicarentals/app/rentals/__init__.py
from flask import Blueprint

rentals = Blueprint('rentals', __name__)

from app.rentals import views

leicarentals/app/rentals/views.py
from flask import (
    render_template,
    redirect,
    request,
)
from flask_login import login_required
from app.rentals import rentals
from app.models import (
    Rental,
)


@rentals.before_request
@login_required
def require_login():
    pass


@rentals.route('/')
@rentals.route('/index')
def index():
    rentals = Rental.query \
        .all()

    return render_template('rentals/index.html',
                           rentals=rentals,
                           title='Rental')


@rentals.route('/new', methods=['GET', 'POST'])
def new():
    return render_template('rentals/new.html',
                           title='Rental')

leicarentals/app/templates/rentals/index.html
{% extends "base.html" %}

{% block app_content %}
  <main class="container mt-4">
   <h2>Rentals</h2>
    <a href="{{ url_for('rentals.new') }}" class="btn btn-link">Create New
      Rental</a>
    {% if rentals %}
       <table id="rentals" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
        <tr>
          <th>Customer</th>
          <th>Lens</th>
          <th>Date Rented</th>
          <th>Return</th>
        </tr>
        </thead>
        <tbody></tbody>
      </table>    
    {% else %}
      <p>There are no rentals.</p>
    {% endif %}
  </main>
{% endblock %}

{% block js %}
<script type="text/javascript">
  $(document).ready(function () {
    var csrf_token = "{{ csrf_token() }}";
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrf_token);
        }
      }
    });
  });
</script>

<script>
  $(document).ready(function () {
    var table = $("#rentals").DataTable({
      ajax: {
        url: "/api/rentals",
        dataSrc: ""
      },
      columns: [
        {
          data: "customer_name",
        },
        {
          data: "lens_name"
        },
        {
          data: "date_rented"
        },
        {
          data: "id",
          render: function(data) {
            return "<button class='btn btn-secondary btn-sm js-delete' data-rentals-id=" + data + ">Return</button>";
          }
        }
      ]
    });

    $("#rentals").on("click", ".js-delete", function () {
      var button = $(this);
        $.ajax({
          url: "/api/rentals/" + button.attr("data-rentals-id"),
          method: "DELETE",
          success: function () {
            table.row(button.parents("tr")).remove().draw();
              new Noty({
                theme: 'rellax',
                type: 'info',
                text: 'Returned!',
              }).setTimeout(1500).show();
          }
        });
      });
  });
</script>
{% endblock %}

leicarentals/app/templates/rentals/new.html
{% extends "base.html" %}

{% block app_content %}
  <main class="container mt-4">
    <div class="row">
      <div class="col-lg-6 col-sm-12">
        <div class="mb-4">
          <h2 class="mb-3">Rental Form</h2>
        </div>
        <form id="rental">
          <div class="form-group">
            <label>Customer</label>
            <div class="tt-container">
              <input id="customer" name="customer" data-rule-validCustomer="true" required type="text" value="" class="form-control" />
            </div>
          </div>
          <div class="form-group">
            <label>Lens</label>
            <div class="tt-container">
              <input id="lens" name="lens" data-rule-atLeastOneLens="true" type="text" value="" class="form-control" />
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-4">
              <ul id="lenses" class="list-group"></ul>
            </div>
          </div>
          <br>
          <button class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </main>
{% endblock %}

{% block js %}

  <script type="text/javascript">
    $(document).ready(function () {
      var csrf_token = "{{ csrf_token() }}";
      $.ajaxSetup({
        beforeSend: function(xhr, settings) {
          if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrf_token);
          }
        }
      });
    });
  </script>
  <script>
    $(document).ready(function () {
        var msg = {
          lensIds: []
        };
        var customers = new Bloodhound({
          datumTokenizer: Bloodhound.tokenizers.obj.whitespace('last_name'),
          queryTokenizer: Bloodhound.tokenizers.whitespace,
          remote: {
            url: '/api/customers?query=%QUERY',
            wildcard: '%QUERY'
          }
        });

        $('#customer').typeahead({
          minLength: 1,
          highlight: true
        }, {
          name: 'customers',
          display: 'full_name',
          source: customers
        }).on("typeahead:select", function(e, customer) {
          msg.customerId = customer.id;
        });
        var lenses = new Bloodhound({
            datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
            queryTokenizer: Bloodhound.tokenizers.whitespace,
            remote: {
                url: '/api/lenses?query=%QUERY',
                wildcard: '%QUERY'
            }
        });
        $('#lens').typeahead({
            minLength: 1,
            highlight: true
        }, {
            name: 'lenses',
            display: 'lens_name',
            source: lenses
        }).on("typeahead:select", function (e, lens) {
            $("#lenses").append("<li class='list-group-item'>" + lens.lens_name + "</li>");
              $("#lens").typeahead("val", "");
              msg.lensIds.push(lens.id);
          });

        $.validator.addMethod("validCustomer", function () {
            return msg.customerId && msg.customerId !== 0;
        }, "<span class='text-primary'>Please select a valid customer.</span>");

        $.validator.addMethod("atLeastOneLens", function () {
            return msg.lensIds.length > 0;
        }, "<span class='text-primary'>Please select atleast one lens.</span>");

        var validator = $("#rental").validate({
            submitHandler: function () {
                console.log(msg);
                $.ajax({
                    url: "/api/rentals/",
                    contentType: "application/json",
                    method: "POST",
                    data: JSON.stringify(msg),
                    dataType: 'json'
                })
                .done(function () {
                    new Noty({
                      theme: 'relax',
                      type: 'alert',
                      text: 'Rentals Recorded'
                    }).setTimeout(1500).show();
                    $("#customer").typeahead("val", "");
                    $("#lens").typeahead("val", "");
                    $("#lenses").empty();
                    msg = { lensIds: [] };
                    validator.resetForm();
                })
                .fail(function () {
                    new Noty({
                      theme: 'relax',
                      type: 'error',
                      text: 'Something Unexpected Happened'
                    }).setTimeout(1500).show();
                });
                return false;
            }
        });
    });
  </script>

{% endblock %}