leicarentals/app/lenses/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SelectField, SubmitField
from wtforms.validators import DataRequired
from wtforms.fields.html5 import DateField


class LensForm(FlaskForm):
    name = StringField('Model', validators=[DataRequired()])
    release_date = DateField(
        'Release Date', format='%Y-%m-%d', validators=[DataRequired()])
    number_in_stock = IntegerField('No. In Stock', validators=[DataRequired()])
    mount_id = SelectField('Mount', coerce=int, validators=[DataRequired()])
    focal_length_id = SelectField(
        'FocalLength', coerce=int, validators=[DataRequired()])
    submit = SubmitField('Submit')

leicarentals/app/lenses/__init__.py
from flask import Blueprint

lenses = Blueprint('lenses', __name__)

from app.lenses import views

leicarentals/app/lenses/views.py
import sys
from flask import (
    render_template,
    flash, redirect,
    url_for,
    request,
)
from flask_login import login_required
from app.lenses.forms import LensForm
from app.extensions import db
from app.lenses import lenses
from app.models import (
    Lens,
    Mount,
    FocalLength,
)


@lenses.before_request
@login_required
def require_login():
    pass


@lenses.route('/')
@lenses.route('/index')
def index():
    lenses = Lens.query \
        .all()

    return render_template('lenses/index.html',
                           lenses=lenses,
                           title='Lenses')


@lenses.route('/new', methods=['GET', 'POST'])
def new():
    mounts = Mount.query \
        .all()
    focal_lengths = FocalLength.query \
        .all()
    form = LensForm()
    form.mount_id.choices = [(f.id, f.name) for f in mounts]
    form.focal_length_id.choices = [(f.id, f.name) for f in focal_lengths]
    if form.validate_on_submit():
        lens = Lens()
        form.populate_obj(lens)
        db.session.add(lens)
        db.session.commit()
        flash('Lens added!', 'success')
        return redirect(url_for('lenses.index'))

    return render_template('lenses/new.html',
                           form=form,
                           title='Lens')


@lenses.route('/edit/<id>', methods=['GET', 'POST'])
def edit(id):
    lens = Lens.query \
               .filter_by(id=id) \
               .first_or_404()
    mounts = Mount.query \
        .all()
    focal_lengths = FocalLength.query \
        .all()
    form = LensForm()
    form = LensForm(obj=lens)
    form.mount_id.choices = [(f.id, f.name) for f in mounts]
    form.focal_length_id.choices = [(f.id, f.name) for f in focal_lengths]
    if form.validate_on_submit():
        form.populate_obj(lens)
        db.session.add(lens)
        db.session.commit()
        flash('Lens updated!', 'success')
        return redirect(url_for('lenses.index'))

    return render_template('lenses/edit.html',
                           form=form,
                           title='Lens')


@lenses.route('/details/<id>')
def details(id):
    lens = Lens.query \
        .filter_by(id=id) \
        .first_or_404()

    return render_template('lenses/details.html',
                           lens=lens,
                           title='Lens')


@lenses.route('/delete/<id>', methods=['POST'])
def delete(id):
    lens = Lens.query \
               .filter_by(id=id) \
               .first_or_404()
    db.session.delete(lens)
    db.session.commit()
    flash('Delete successfully.', 'success')

    return redirect(url_for('lenses.index'))

leicarentals/app/templates/lenses/details.html
{% extends "base.html" %}

{% block app_content %}
  <main class="container mt-4">
    <div class="col-lg-6 col-sm-12">
    <h2>{{ lens.name }}</h2>
    <ul class="list-group">
      <li class="list-group-item">Name: {{ lens.name }}</li>
      <li class="list-group-item">Release Date: {{ lens.release_date.strftime('%Y-%m-%d') }}</li>
      <li class="list-group-item">Mount: {{ lens.mount.name }}</li>
      <li class="list-group-item">Focal Length: {{ lens.focal_length.name }}</li>
      <li class="list-group-item">Date Added: {{ lens.date_added.strftime('%Y-%m-%d') }}</li>
      <li class="list-group-item">Number in stock: {{ lens.number_in_stock }}</li>
      <li class="list-group-item">Number available: {{ lens.number_available }}</li>
    </ul>
    </div>
  </main>
{% endblock %}

leicarentals/app/templates/lenses/edit.html
{% extends "base.html" %}

{% block app_content %}
  <main class="container mt-4">
    <div class="col-lg-6 col-sm-12">
      <div class="mb-4">
        <h2 class="mb-3">Lens Form</h2>
      </div>
      <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.name.label }}
          {{ form.name(class_="form-control") }}
          {% for error in form.name.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.release_date.label }}
          {{ form.release_date(class_="form-control") }}
          {% for error in form.release_date.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.mount_id.label }}
          {{ form.mount_id(class_="form-control") }}
          {% for error in form.mount_id.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.focal_length_id.label }}
          {{ form.focal_length_id(class_="form-control") }}
          {% for error in form.focal_length_id.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.number_in_stock.label }}
          {{ form.number_in_stock(class_="form-control") }}
          {% for error in form.number_in_stock.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
        {{ form.submit(class="ui fluid large submit button") }}
      </form>
    </div>
  </main>
{% endblock %}

leicarentals/app/templates/lenses/index.html
{% extends "base.html" %}

{% block app_content %}
  <main class="container mt-4">
   <h2>Lenses</h2>
    <a href="{{ url_for('lenses.new') }}" class="btn btn-link">Add New Lens</a>
    {% if lenses %}
       <table id="lenses" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
        <tr>
          <th>Lenses</th>
          <th>Mount</th>
          <th>Focal Length</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
        </thead>
        <tbody></tbody>
      </table>    
    {% else %}
      <p>We don't have any lenses yet.</p>
    {% endif %}
  </main>
{% endblock %}

{% block js %}

<script type="text/javascript">
  $(document).ready(function () {
    var csrf_token = "{{ csrf_token() }}";
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrf_token);
        }
      }
    });
  });
</script>

<script>
  $(document).ready(function () {
    var table = $("#lenses").DataTable({
      ajax: {
        url: "/api/lenses",
        dataSrc: ""
      },
      columns: [
        {
          data: "name",
          render: function(data, type, lens) {
            return "<a href='/lenses/details/" + lens.id + "'>" + lens.lens_name + "</a>";
          }
        },
        {
          data: "mount_name"
        },
        {
          data: "focal_length_name"
        },
        {
          data: "name",
          render: function(data, type, lens) {
              return "<a href='/lenses/edit/" + lens.id + "'class='btn btn-secondary btn-sm'>Edit</a>";
          }
        },
        {
          data: "id",
          render: function(data) {
            return "<button class='btn btn-secondary btn-sm js-delete' data-lens-id=" + data + ">Delete</button>";
          }
        }
      ]
    });
  });
</script>

<script>
  $("#lenses").on("click", ".js-delete", function () {
    var button = $(this);
    bootbox.confirm("Are you sure you want to delete this lens?", function (result) {
      if (result) {
        $.ajax({
          url: "/api/lenses/" + button.attr("data-lens-id"),
          method: "DELETE",
          success: function () {
            table.row(button.parents("tr")).remove().draw();
          }
        });
      }
    });
  });
</script>
{% endblock %}

leicarentals/app/templates/lenses/new.html
{% extends "base.html" %}

{% block app_content %}
  <main class="container mt-4">
    <div class="col-lg-6 col-sm-12">
      <div class="mb-4">
        <h2 class="mb-3">Lens Form</h2>
      </div>
      <form id="newLensForm" action="" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.name.label }}
          {{ form.name(class_="form-control") }}
          {% for error in form.name.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.release_date.label }}
          {{ form.release_date(class_="form-control" ) }}
          {% for error in form.release_date.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.mount_id.label }}
          {{ form.mount_id(class_="form-control") }}
          {% for error in form.mount_id.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.focal_length_id.label }}
          {{ form.focal_length_id(class_="form-control") }}
          {% for error in form.focal_length_id.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.number_in_stock.label }}
          {{ form.number_in_stock(class_="form-control") }}
          {% for error in form.number_in_stock.errors %}
            <span class="text-primary">{{ error }}</span>
          {% endfor %}
        </div>
        {{ form.submit(class="btn btn-primary") }}
      </form>
    </div>
  </main>
{% endblock %}